# Generated by Django 6.0.5 on 2026-07-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.CharField(choices=[('NOURRITURE', 'Nourriture'), ('TRANSPORT', 'Transport'), ('LOGEMENT', 'Logement'), ('LOISIRS', 'Loisirs'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
